# Band 05 · Übungsarchiv — 300 Übungen
# 12 Kategorien x 25 Übungen. Zeile: (Kategorie, Übung, Ziel, Dauer, Alter)
ARCHIV = [
("Kategorie", "Übung", "Ziel", "Dauer", "Alter"),
("Technik", "Dribbel-Slalom", "Ballführung mit Tempo", "15 Min", "U8–U10"),
("Technik", "Finten-Parcours", "Körpertäuschungen anwenden", "15 Min", "U11–U12"),
("Technik", "Übersteiger-Schule", "Übersteiger gezielt einsetzen", "15 Min", "U13–U14"),
("Technik", "Schwacher Fuß – Tunnel", "Beidfüßigkeit trainieren", "15 Min", "U11–U14"),
("Technik", "Ballzirkus", "Ballgefühl und Tricks", "15 Min", "U8–U12"),
("Technik", "Mitnahme-Parcours", "Ballmitnahme in Bewegung", "15 Min", "U11–U14"),
("Technik", "Innenseite-Serie", "Präzise Pässe mit der Innenseite", "15 Min", "U8–U12"),
("Technik", "Außenrist-Schule", "Pässe und Flanken mit dem Außenrist", "20 Min", "U13–U18"),
("Technik", "Ballannahme unter Druck", "Sichere Ballkontrolle", "20 Min", "U13–U18"),
("Technik", "Flugball-Technik", "Hohe Pässe kontrollieren", "20 Min", "U13–U18"),
("Technik", "Volley-Schule", "Volleyabschlüsse trainieren", "20 Min", "U13–U18"),
("Technik", "Kopfball-Grundlagen", "Kopfballtechnik verbessern", "15 Min", "U13–U18"),
("Technik", "Dribbling im Rondo", "Ballkontrolle im Gedränge", "20 Min", "U11–U14"),
("Technik", "Tempowechsel-Dribbling", "Antritt und Tempo", "15 Min", "U11–U14"),
("Technik", "Rückwärts-Dribbling", "Orientierung und Ballkontrolle", "15 Min", "U11–U14"),
("Technik", "Fersen-Drehung", "Drehungen mit Ball", "15 Min", "U11–U14"),
("Technik", "Ballhalten im Zweikampf", "Körper richtig einsetzen", "20 Min", "U13–U18"),
("Technik", "Enge Ballführung", "Ballführung auf engem Raum", "15 Min", "U8–U12"),
("Technik", "Laufwege mit Ball", "Dribbling in Laufwegen", "15 Min", "U11–U14"),
("Technik", "Trick-Show", "Tricks kombinieren", "15 Min", "U8–U12"),
("Technik", "Dribbel-Sprint", "Tempo mit Ball", "15 Min", "U11–U14"),
("Technik", "Ballstopp-Schule", "Ball stoppen und weiter", "15 Min", "U8–U12"),
("Technik", "Doppelte Ballführung", "Zwei Bälle kontrollieren", "20 Min", "U11–U14"),
("Technik", "Ballheben", "Ballkontrolle in der Luft", "15 Min", "U13–U18"),
("Technik", "Technik-Zirkel", "Runde Technikstationen", "20 Min", "U8–U14"),
("Passspiel", "Rondo 3:1", "Erste Passerfahrungen", "15 Min", "U8–U10"),
("Passspiel", "Rondo 4:2", "Schnelles Passen", "20 Min", "U11–U12"),
("Passspiel", "Dreieckspassspiel", "Anbieten und Passen", "15 Min", "U11–U14"),
("Passspiel", "Pass-Dreieck mit Bewegung", "Bewegung nach dem Pass", "15 Min", "U10–U12"),
("Passspiel", "Doppelpass-Kette", "Doppelpässe kombinieren", "20 Min", "U13–U18"),
("Passspiel", "Spielverlagerung", "Wechsel der Angriffsseite", "20 Min", "U13–U18"),
("Passspiel", "Pass-Tore", "Durch Pass-Tore spielen", "15 Min", "U8–U10"),
("Passspiel", "Zwei-Kontakt-Spiel", "Schnelles Zwei-Kontakt-Passen", "20 Min", "U11–U14"),
("Passspiel", "Pass auf drei Farben", "Reaktion auf Farben", "15 Min", "U8–U10"),
("Passspiel", "Überzahl-Passspiel 5:2", "Ballbesitz in Überzahl", "20 Min", "U13–U14"),
("Passspiel", "Passstaffel", "Passgenauigkeit im Wettkampf", "15 Min", "U8–U12"),
("Passspiel", "Halbfeld-Pässe", "Räume im Halbfeld finden", "20 Min", "U15–U18"),
("Passspiel", "Flugball-Passspiel", "Hohe Pässe annehmen", "20 Min", "U13–U18"),
("Passspiel", "Passen im Quadrat", "Passspiel in Bewegung", "15 Min", "U11–U14"),
("Passspiel", "Außenrist-Pässe", "Pässe mit dem Außenrist", "20 Min", "U13–U18"),
("Passspiel", "Kurzer und langer Pass", "Passdistanzen variieren", "20 Min", "U11–U14"),
("Passspiel", "Pass unter Gegnerdruck", "Passen mit Druck", "20 Min", "U13–U18"),
("Passspiel", "Dreiecksspiel mit Laufweg", "Kombinationen in Dreiecken", "20 Min", "U13–U14"),
("Passspiel", "Pass in die Tiefe", "Vertikalspiel üben", "20 Min", "U13–U18"),
("Passspiel", "Spiel auf den dritten Mann", "Kombinationspass", "20 Min", "U13–U18"),
("Passspiel", "Pass-Rondo mit Joker", "Überzahl nutzen", "15 Min", "U11–U14"),
("Passspiel", "Schatten-Passen", "Passen ohne Ball", "15 Min", "U8–U12"),
("Passspiel", "Tempopass", "Pässe mit Tempo", "15 Min", "U11–U14"),
("Passspiel", "Fünf-Pässe-Regel", "Nach fünf Pässen Torschuss", "20 Min", "U11–U14"),
("Passspiel", "Ballzirkulation im Rondo", "Ruhiger Ballbesitz", "20 Min", "U13–U18"),
("Ballbesitz", "Quadrat 5:2", "Ballbesitz in Überzahl", "20 Min", "U11–U14"),
("Ballbesitz", "Positionsspiel 6:4", "Positionsdisziplin", "20 Min", "U13–U14"),
("Ballbesitz", "Ballzirkulation", "Geduld und Präzision", "15 Min", "U11–U14"),
("Ballbesitz", "Positionsspiel 8:5", "Hohe Ballzirkulation", "25 Min", "U15–U18"),
("Ballbesitz", "Rondo mit Joker", "Überzahl ausnutzen", "15 Min", "U13–U18"),
("Ballbesitz", "Freie Anspielstation", "Freilaufen und Anbieten", "20 Min", "U15–U18"),
("Ballbesitz", "Ballbesitz im Quadrat", "Geduldiger Ballbesitz", "20 Min", "U11–U14"),
("Ballbesitz", "Acht-Pässe-Punkte", "Punkte für Passfolgen", "20 Min", "U11–U14"),
("Ballbesitz", "Dreier-Team-Ballbesitz", "Kurze Kombinationen", "15 Min", "U8–U12"),
("Ballbesitz", "Ballbesitz unter Zeitdruck", "Schnelles Umschalten", "20 Min", "U13–U18"),
("Ballbesitz", "Spiel auf die Endzone", "Ballbesitz in Zonen", "20 Min", "U13–U18"),
("Ballbesitz", "Feld vergrößern", "Spielfeld groß halten", "20 Min", "U15–U18"),
("Ballbesitz", "Zwei-Kontakt-Rondo", "Schnelles Passen", "20 Min", "U13–U18"),
("Ballbesitz", "Ballbesitz 7:3", "Deutliche Überzahl", "20 Min", "U13–U14"),
("Ballbesitz", "Rondo mit Wechsel", "Positionen wechseln", "15 Min", "U11–U14"),
("Ballbesitz", "Tempo- und Rhythmuswechsel", "Spielrhythmus bestimmen", "20 Min", "U15–U18"),
("Ballbesitz", "Joker an der Linie", "Breite und Tiefe", "20 Min", "U13–U18"),
("Ballbesitz", "Ballbesitz 9:6", "Viel Ballkontakt", "25 Min", "U15–U18"),
("Ballbesitz", "Ruhe im Ballbesitz", "Geduld statt Hektik", "20 Min", "U15–U18"),
("Ballbesitz", "Anbieten im Rondo", "Anbietbewegungen", "15 Min", "U11–U12"),
("Ballbesitz", "Passspiel ohne Gegner", "Grundlagen des Ballbesitzes", "15 Min", "U8–U10"),
("Ballbesitz", "Ballbesitz mit Torhüter", "Torhüter einbinden", "25 Min", "U13–U18"),
("Ballbesitz", "Sechser-Passspiel", "Zentrale Kombinationen", "20 Min", "U13–U18"),
("Ballbesitz", "Dreieck zirkulieren", "Ball im Dreieck laufen lassen", "15 Min", "U8–U12"),
("Ballbesitz", "Überzahl-Kette", "Ketten-Ballbesitz", "20 Min", "U11–U14"),
("Taktik", "Umschaltspiel 3:2", "Schnelles Umschalten", "20 Min", "U13–U14"),
("Taktik", "Pressing-Viererblock", "Gemeinsames Pressing", "25 Min", "U13–U18"),
("Taktik", "Gegenpressing", "Ball sofort attackieren", "20 Min", "U15–U18"),
("Taktik", "Spielaufbau von hinten", "Sicherer Aufbau", "25 Min", "U13–U18"),
("Taktik", "Tiefenläufe", "Läufe in die Tiefe", "20 Min", "U13–U18"),
("Taktik", "Halbräume bespielen", "Anspruchsvolle Kombinationen", "25 Min", "U15–U18"),
("Taktik", "Verschieben als Einheit", "Gemeinsames Verschieben", "20 Min", "U13–U18"),
("Taktik", "Anlaufen nach Abstoß", "Pressing nach Abstoß", "25 Min", "U15–U18"),
("Taktik", "Passwege schließen", "Passwege verstellen", "20 Min", "U13–U18"),
("Taktik", "Doppeln im Pressing", "Zweikampf-Doppeln", "20 Min", "U15–U18"),
("Taktik", "Kette kompakt", "Kompaktheit der Kette", "20 Min", "U15–U18"),
("Taktik", "Abseitsfalle", "Geordnetes Vorrücken", "25 Min", "U15–U18"),
("Taktik", "System 4-3-3 Grundordnung", "Grundordnung einhalten", "25 Min", "U15–U18"),
("Taktik", "System 4-4-2", "Formation umsetzen", "25 Min", "U15–U18"),
("Taktik", "Staffelung im Angriff", "Staffelung der Angreifer", "20 Min", "U15–U18"),
("Taktik", "Gegenpressing 5:4", "Sofort attackieren", "25 Min", "U15–U18"),
("Taktik", "Sechs-Sekunden-Regel", "Ball schnell erobern", "20 Min", "U13–U18"),
("Taktik", "Raumgewinn nach Balleroberung", "Nach Ballgewinn vorwärts", "20 Min", "U15–U18"),
("Taktik", "Positionen fixieren", "Positionsdisziplin", "20 Min", "U11–U14"),
("Taktik", "Doppelpass als Mittel", "Doppelpass bewusst einsetzen", "20 Min", "U13–U18"),
("Taktik", "Überzahl im Zentrum", "Zentrale Überzahl", "20 Min", "U15–U18"),
("Taktik", "Dritte Zone attackieren", "Schnelles Vorwärtsspiel", "20 Min", "U13–U18"),
("Taktik", "Außenverteidiger überlappen", "Überlappungen", "25 Min", "U15–U18"),
("Taktik", "Doppel-6 im Zentrum", "Zentrales Mittelfeld", "25 Min", "U15–U18"),
("Taktik", "Spiel in den Halbraum", "Halbräume gezielt nutzen", "20 Min", "U13–U18"),
("Abschluss", "Torschuss aus dem Lauf", "Abschluss in Bewegung", "20 Min", "U11–U14"),
("Abschluss", "Farbtore", "Gezielter Torschuss", "20 Min", "U8–U10"),
("Abschluss", "Abschluss nach Passfolge", "Kombinationen vor dem Tor", "25 Min", "U13–U18"),
("Abschluss", "Volley-Abschluss", "Volleyabschluss trainieren", "20 Min", "U13–U18"),
("Abschluss", "Schuss-Wettbewerb", "Präzision unter Druck", "20 Min", "U13–U18"),
("Abschluss", "Bewegte Tore", "Timing des Abschlusses", "15 Min", "U8–U12"),
("Abschluss", "Abschluss nach Flanke", "Flanken verwerten", "25 Min", "U13–U18"),
("Abschluss", "Abschluss unter Zeitdruck", "Schnelle Abschlüsse", "20 Min", "U13–U18"),
("Abschluss", "Tor aus dem Dribbling", "Abschluss nach Dribbling", "20 Min", "U11–U14"),
("Abschluss", "Erster Schuss", "Direkter Abschluss", "20 Min", "U11–U14"),
("Abschluss", "Kopfball-Abschluss", "Kopfballtreffer", "20 Min", "U13–U18"),
("Abschluss", "Abschluss nach Doppelpass", "Kombinationsabschluss", "20 Min", "U13–U18"),
("Abschluss", "Torwart-Training Abschluss", "Abschluss gegen Torhüter", "25 Min", "U13–U18"),
("Abschluss", "Spitzwinkel-Tore", "Aus dem Winkel treffen", "20 Min", "U13–U18"),
("Abschluss", "Abschluss nach Ballannahme", "Annahme und Schuss", "20 Min", "U11–U14"),
("Abschluss", "Sechs-Meter-Schüsse", "Kurze Abschlüsse", "15 Min", "U8–U10"),
("Abschluss", "Schussfolge in Teams", "Team-Schussstationen", "20 Min", "U11–U14"),
("Abschluss", "Weitschüsse", "Tore aus der Distanz", "20 Min", "U13–U18"),
("Abschluss", "Abschluss im 2:1", "Überzahl abschließen", "20 Min", "U13–U18"),
("Abschluss", "Beweglicher Torhüter", "Platzierte Schüsse", "20 Min", "U11–U14"),
("Abschluss", "Schuss-Tunnel", "Präzise Flachschüsse", "15 Min", "U8–U12"),
("Abschluss", "Abschluss nach Außenrist", "Technischer Abschluss", "20 Min", "U15–U18"),
("Abschluss", "Elfmeter-Schule", "Elfmeter sicher verwandeln", "20 Min", "U11–U18"),
("Abschluss", "Abschluss-Wettkampf", "Punkte für Treffer", "20 Min", "U11–U14"),
("Abschluss", "Minitore bespielen", "Viele kleine Tore", "15 Min", "U8–U10"),
("1 gegen 1", "König des Spielfelds", "Duelle mutig lösen", "20 Min", "U8–U10"),
("1 gegen 1", "Duelle mit Abschluss", "1:1 mit Torschuss", "25 Min", "U11–U14"),
("1 gegen 1", "1:1 vor dem Tor", "Duelle im Strafraum", "25 Min", "U13–U18"),
("1 gegen 1", "Finten-Wettkampf", "Finten im Duell", "20 Min", "U11–U14"),
("1 gegen 1", "1:1 mit Torhüter", "Abschluss gegen Torwart", "25 Min", "U13–U18"),
("1 gegen 1", "K.o.-Turnier", "Wettkampf-Duelle", "20 Min", "U13–U18"),
("1 gegen 1", "1:1 auf 4 Minitore", "Viele Tore", "20 Min", "U8–U12"),
("1 gegen 1", "Verteidigen im 1:1", "Gegenhalten und klären", "20 Min", "U13–U18"),
("1 gegen 1", "Rücken zum Tor", "Drehungen im Duell", "20 Min", "U13–U18"),
("1 gegen 1", "1:1 im Tunnel", "Platz für den Abschluss", "20 Min", "U11–U14"),
("1 gegen 1", "Startpositionen-Duell", "Aus verschiedenen Lagen", "20 Min", "U13–U18"),
("1 gegen 1", "Schatten-Duell", "Nachziehen und attackieren", "15 Min", "U11–U14"),
("1 gegen 1", "1:1 mit Zeitlimit", "Schnelle Entscheidungen", "20 Min", "U13–U18"),
("1 gegen 1", "Dribbel-Duelle", "Dribbling im Duell", "15 Min", "U8–U12"),
("1 gegen 1", "Seitwärts-Duell", "Seitwärts angreifen", "20 Min", "U11–U14"),
("1 gegen 1", "Übersteiger-Duell", "Übersteiger im Duell", "20 Min", "U13–U18"),
("1 gegen 1", "Ball halten", "Ball abschirmen", "20 Min", "U11–U14"),
("1 gegen 1", "Zwei Bälle – zwei Duelle", "Gleichzeitig Duell", "20 Min", "U13–U18"),
("1 gegen 1", "Jagd-Duell", "Ball jagen und erobern", "15 Min", "U8–U10"),
("1 gegen 1", "Torschuss-Duell", "Wer trifft zuerst", "20 Min", "U11–U14"),
("1 gegen 1", "1:1 in der Zone", "Duelle in der Endzone", "20 Min", "U13–U18"),
("1 gegen 1", "Kopfball-Duell", "Luftduelle", "15 Min", "U13–U18"),
("1 gegen 1", "Schwacher-Fuß-Duell", "Beidfüßig im Duell", "20 Min", "U13–U18"),
("1 gegen 1", "Kontakt-Duell", "Körperkontakt zulassen", "20 Min", "U13–U18"),
("1 gegen 1", "Mini-Liga 1:1", "Duell-Liga", "20 Min", "U11–U14"),
("Flügelspiel", "Flügel 3:2", "Überzahl auf dem Flügel", "20 Min", "U13–U14"),
("Flügelspiel", "Flanken und Abschluss", "Flanken verwerten", "25 Min", "U13–U18"),
("Flügelspiel", "Verlagerung auf den Flügel", "Seitenwechsel", "25 Min", "U15–U18"),
("Flügelspiel", "Flügelspiel mit Joker", "Anspielstation außen", "20 Min", "U13–U18"),
("Flügelspiel", "Kopfball-Schule", "Kopfballtechnik", "20 Min", "U13–U18"),
("Flügelspiel", "Hinterlaufen", "Läufe über außen", "20 Min", "U15–U18"),
("Flügelspiel", "Flügel-Dribbling", "Über außen dribbeln", "20 Min", "U11–U14"),
("Flügelspiel", "Doppelpass auf dem Flügel", "Kombinationen außen", "20 Min", "U13–U18"),
("Flügelspiel", "Flache Hereingaben", "Flache Bälle in den Strafraum", "20 Min", "U13–U18"),
("Flügelspiel", "Außenverteidiger mitlaufen", "Mitläufe außen", "25 Min", "U15–U18"),
("Flügelspiel", "Dribbling gegen die Linie", "Zur Grundlinie kombinieren", "20 Min", "U13–U18"),
("Flügelspiel", "Flügel-Trio", "Drei auf dem Flügel", "25 Min", "U15–U18"),
("Flügelspiel", "Weite Verlagerung", "Lange Bälle wechseln", "20 Min", "U13–U18"),
("Flügelspiel", "Innenverteidiger auf den Flügel", "Außen öffnen", "25 Min", "U15–U18"),
("Flügelspiel", "Flügelspiel mit Abschluss", "Flügelangriff vollenden", "25 Min", "U13–U18"),
("Flügelspiel", "Breite und Tiefe", "Spielfeld nutzen", "20 Min", "U13–U18"),
("Flügelspiel", "Flankenlauf und Tor", "Laufweg in den Strafraum", "20 Min", "U13–U18"),
("Flügelspiel", "Kurzpass auf dem Flügel", "Kurze Kombinationen", "15 Min", "U11–U14"),
("Flügelspiel", "Flügel gegen Flügel", "Duelle außen", "20 Min", "U13–U18"),
("Flügelspiel", "Schneller Flügelangriff", "Tempo über außen", "20 Min", "U15–U18"),
("Flügelspiel", "Joker in der Halbspur", "Anspiele im Halbraum", "20 Min", "U15–U18"),
("Flügelspiel", "Ecken-Doppelpass", "Ecken kurz kombinieren", "20 Min", "U13–U18"),
("Flügelspiel", "Flügelspiel 2:1", "Überzahl herstellen", "20 Min", "U13–U14"),
("Flügelspiel", "Lauf in die Tiefe außen", "Tiefenläufe über außen", "20 Min", "U15–U18"),
("Flügelspiel", "Flügel-Finte", "Finten auf dem Flügel", "20 Min", "U13–U18"),
("Spielaufbau", "Aufbau 5:3", "Aufbau gegen Pressing", "25 Min", "U13–U14"),
("Spielaufbau", "Aufbau mit Torhüter", "Torhüter einbinden", "25 Min", "U13–U18"),
("Spielaufbau", "Aufbau 8:6", "Aufbau gegen intensive Störer", "25 Min", "U15–U18"),
("Spielaufbau", "Dritte Zone", "Schnelles Vorwärtsspiel", "25 Min", "U13–U18"),
("Spielaufbau", "Joker hinter der Kette", "Tiefe Anspielstation", "20 Min", "U13–U18"),
("Spielaufbau", "Aufbau unter Zeitdruck", "Schnelle Entscheidungen", "25 Min", "U15–U18"),
("Spielaufbau", "Erste Passoption", "Den ersten Pass finden", "20 Min", "U13–U18"),
("Spielaufbau", "Spiel über die Sechser", "Zentrale Aufbauwege", "25 Min", "U15–U18"),
("Spielaufbau", "Aufbau aus dem Abstoß", "Sicherer Abstoß", "25 Min", "U13–U18"),
("Spielaufbau", "Ball aus der Box", "Ruhig aus der Abwehr", "20 Min", "U13–U18"),
("Spielaufbau", "Drei-Mann-Kette", "Aufbau in der Dreierkette", "25 Min", "U15–U18"),
("Spielaufbau", "Vierer-Kette aufbauen", "Kette flach stellen", "25 Min", "U15–U18"),
("Spielaufbau", "Freilaufen im Aufbau", "Anbieten im Aufbau", "20 Min", "U11–U14"),
("Spielaufbau", "Zweikampfvermeidung", "Vor dem Zweikampf lösen", "20 Min", "U15–U18"),
("Spielaufbau", "Diagonaler Aufbau", "Diagonalpässe im Aufbau", "20 Min", "U13–U18"),
("Spielaufbau", "Aufbau über die Außen", "Außen einbeziehen", "25 Min", "U13–U18"),
("Spielaufbau", "Tempoaufbau", "Ruhig und schnell aufbauen", "20 Min", "U15–U18"),
("Spielaufbau", "Fallenlassen des Sechsers", "Sechser ins Aufbauspiel", "25 Min", "U15–U18"),
("Spielaufbau", "Dreiecke im Aufbau", "Dreieckskombinationen", "20 Min", "U13–U18"),
("Spielaufbau", "Aufbau gegen Manndeckung", "Gegen enge Deckung", "25 Min", "U15–U18"),
("Spielaufbau", "Kurze Pässe aus der Abwehr", "Kurze Aufbauwege", "20 Min", "U11–U14"),
("Spielaufbau", "Spielverlagerung im Aufbau", "Seitenwechsel früh", "20 Min", "U13–U18"),
("Spielaufbau", "Gegenpressing im Aufbau", "Nach Ballverlust sofort", "25 Min", "U15–U18"),
("Spielaufbau", "Aufbau mit Überzahl", "Überzahl im Aufbau", "25 Min", "U13–U18"),
("Spielaufbau", "Tiefe Anspielstation", "Tiefe Pässe finden", "20 Min", "U13–U18"),
("Koordination", "Hütchen-Zirkel", "Koordination mit Ball", "20 Min", "U8–U12"),
("Koordination", "Tierparcours", "Ballgewöhnung", "15 Min", "U8–U10"),
("Koordination", "Koordinationsleitern", "Fußschnelligkeit", "15 Min", "U10–U14"),
("Koordination", "Spiegeltraining", "Reaktion und Koordination", "15 Min", "U8–U12"),
("Koordination", "Staffel-Läufe mit Ball", "Schnelligkeit mit Ball", "15 Min", "U10–U14"),
("Koordination", "Zwei Bälle", "Koordination unter Druck", "20 Min", "U11–U14"),
("Koordination", "Hüpfen und Prellen", "Prellen mit dem Ball", "15 Min", "U8–U10"),
("Koordination", "Reaktions-Dribbling", "Schnelle Richtungswechsel", "15 Min", "U8–U12"),
("Koordination", "Koordinations-Zirkel", "Vier Stationen", "20 Min", "U10–U14"),
("Koordination", "Balancieren mit Ball", "Gleichgewicht", "15 Min", "U8–U12"),
("Koordination", "Springen und Passen", "Kombinationen von Bewegungen", "15 Min", "U8–U12"),
("Koordination", "Rückwärtslaufen mit Ball", "Raumwahrnehmung", "15 Min", "U10–U14"),
("Koordination", "Seitwärts-Dribbling", "Seitwärts bewegen", "15 Min", "U8–U12"),
("Koordination", "Hüpfkästchen mit Ball", "Fußschnelligkeit", "15 Min", "U8–U10"),
("Koordination", "Ball und Matte", "Wechsel der Untergründe", "20 Min", "U11–U14"),
("Koordination", "Partner-Reaktion", "Reaktion auf Kommandos", "15 Min", "U8–U12"),
("Koordination", "Slalom-Sprünge", "Sprungkoordination", "15 Min", "U8–U10"),
("Koordination", "Dribbling mit Hindernissen", "Ball und Hindernisse", "15 Min", "U8–U12"),
("Koordination", "Koordinations-Parcours", "Mehrere Aufgaben", "20 Min", "U10–U14"),
("Koordination", "Schatten mit Ball", "Bewegungen nachahmen", "15 Min", "U8–U10"),
("Koordination", "Drehungen mit Ball", "Drehkoordination", "15 Min", "U8–U12"),
("Koordination", "Wechselsprünge", "Beinkoordination", "15 Min", "U10–U14"),
("Koordination", "Ball führen mit beiden Füßen", "Beidfüßige Führung", "15 Min", "U11–U14"),
("Koordination", "Schnelles Umspringen", "Umkehrbewegungen", "15 Min", "U10–U14"),
("Koordination", "Zirkel mit Musik", "Koordination mit Spaß", "20 Min", "U8–U12"),
("Fangspiele", "Jäger und Freie", "Dribbling unter Druck", "15 Min", "U8–U10"),
("Fangspiele", "Dschungel-Ball", "Orientierung mit Ball", "15 Min", "U8–U10"),
("Fangspiele", "Völkerball mit Füßen", "Passen unter Druck", "20 Min", "U8–U12"),
("Fangspiele", "Farb-Jagd", "Reaktion und Dribbling", "15 Min", "U8–U10"),
("Fangspiele", "Ball entern", "Balleroberung spielerisch", "20 Min", "U10–U12"),
("Fangspiele", "Ketten-Fangen", "Teamwork und Ausweichen", "15 Min", "U8–U12"),
("Fangspiele", "Zonen-Jäger", "Ballbesitz schützen", "15 Min", "U8–U12"),
("Fangspiele", "Käfig-Jagd", "Fangen im Käfig", "15 Min", "U8–U10"),
("Fangspiele", "Schatten-Jäger", "Fangen mit Ball", "15 Min", "U8–U10"),
("Fangspiele", "Bewegliche Inseln", "Sicherheitszonen", "15 Min", "U8–U10"),
("Fangspiele", "Team-Jäger", "Jäger-Teams", "15 Min", "U8–U12"),
("Fangspiele", "Eroberer", "Bälle erobern", "15 Min", "U8–U10"),
("Fangspiele", "Schwänzchen ziehen", "Dribbling und Entwischen", "15 Min", "U8–U10"),
("Fangspiele", "Drache und Ritter", "Gemeinsames Verteidigen", "15 Min", "U8–U10"),
("Fangspiele", "Blitz-Jagd", "Schnell reagieren", "15 Min", "U8–U10"),
("Fangspiele", "Vier-Ecken-Jäger", "Fangen im Quadrat", "15 Min", "U8–U12"),
("Fangspiele", "Jäger mit Ball", "Dribbling und Fangen", "15 Min", "U8–U10"),
("Fangspiele", "Riesen-Fangen", "Großes Feld", "15 Min", "U8–U10"),
("Fangspiele", "Roboter-Jäger", "Fangen mit Vorgaben", "15 Min", "U8–U10"),
("Fangspiele", "Pinguin-Fangen", "Fangen ohne Ballkontakt", "15 Min", "U8–U10"),
("Fangspiele", "Torwächter", "Tore schützen", "15 Min", "U8–U10"),
("Fangspiele", "Bunte Bälle", "Farben und Fangen", "15 Min", "U8–U10"),
("Fangspiele", "Eis-Zone", "Einfrieren im Spiel", "15 Min", "U8–U10"),
("Fangspiele", "Jagd-Parcours", "Fangen im Parcours", "15 Min", "U8–U12"),
("Fangspiele", "Tiger-Jagd", "Dribbling gegen Fänger", "15 Min", "U8–U10"),
("Standards", "Ecken offensiv", "Ecken mit Laufwegen", "25 Min", "U13–U18"),
("Standards", "Ecken defensiv", "Klären und Kontern", "25 Min", "U13–U18"),
("Standards", "Freistöße direkt", "Direkte Freistöße", "25 Min", "U15–U18"),
("Standards", "Freistöße defensiv", "Mauer und Absicherung", "25 Min", "U13–U18"),
("Standards", "Einwürfe", "Sichere Einwürfe", "15 Min", "U10–U14"),
("Standards", "Abstoß-Varianten", "Spielaufbau nach Abstoß", "25 Min", "U13–U18"),
("Standards", "Ecken kurz", "Kurze Ecken kombinieren", "20 Min", "U13–U18"),
("Standards", "Ecken mit Blockern", "Blocker einsetzen", "25 Min", "U15–U18"),
("Standards", "Freistoß-Mauer", "Mauer richtig stellen", "20 Min", "U13–U18"),
("Standards", "Freistoß-Varianten", "Verschiedene Freistöße", "25 Min", "U15–U18"),
("Standards", "Indirekte Freistöße", "Kombinierte Freistöße", "20 Min", "U13–U18"),
("Standards", "Ecken-Restverteidigung", "Absicherung bei Ecken", "25 Min", "U13–U18"),
("Standards", "Kopfball-Ecken", "Ecken mit Kopfball", "25 Min", "U13–U18"),
("Standards", "Freistoß aus der Distanz", "Weite Freistöße", "20 Min", "U15–U18"),
("Standards", "Seitenlinien-Einwürfe", "Weite Einwürfe", "15 Min", "U13–U18"),
("Standards", "Eckball-Falle", "Abseits bei Ecken", "25 Min", "U15–U18"),
("Standards", "Freistoß-Spielzug", "Einstudierte Spielzüge", "25 Min", "U15–U18"),
("Standards", "Ecken mit Rückraum", "Rückraum absichern", "25 Min", "U15–U18"),
("Standards", "Abstoß kurz", "Kurzer Abstoß", "20 Min", "U13–U18"),
("Standards", "Abstoß lang", "Langer Abstoß", "20 Min", "U13–U18"),
("Standards", "Mauer-Sprung", "Mauer springt", "20 Min", "U13–U18"),
("Standards", "Freistoß-Torschuss", "Freistöße mit Abschluss", "20 Min", "U13–U18"),
("Standards", "Ecken-Turnier", "Ecken im Wettbewerb", "25 Min", "U13–U18"),
("Standards", "Standard-Kombinationen", "Alle Standards kombinieren", "25 Min", "U15–U18"),
("Standards", "Foulspiel-Situationen", "Freistöße nach Foul", "20 Min", "U13–U18"),
("Spielformen", "3 gegen 3 auf 4 Tore", "Viel Ballkontakt", "20 Min", "U8–U12"),
("Spielformen", "5 gegen 5 mit Joker", "Überzahl nutzen", "25 Min", "U11–U14"),
("Spielformen", "Zonen-Spiel", "Räume bespielen", "25 Min", "U13–U18"),
("Spielformen", "Kleinfeld-Turnier", "Wettkampf mit Spaß", "25 Min", "U11–U14"),
("Spielformen", "Farb-Teams", "Teams nach Farben", "20 Min", "U8–U12"),
("Spielformen", "Joker-Teams", "Joker einsetzen", "20 Min", "U11–U14"),
("Spielformen", "Drei-Zonen-Spiel", "Zonenregeln", "25 Min", "U13–U18"),
("Spielformen", "Spiel auf Ballbesitz", "Ballbesitz belohnen", "25 Min", "U13–U18"),
("Spielformen", "Mini-Weltmeisterschaft", "Turnierform", "25 Min", "U8–U12"),
("Spielformen", "Spiel mit Handicap", "Mit Vorgaben spielen", "20 Min", "U11–U14"),
("Spielformen", "Riesen-Tor", "Große Tore", "20 Min", "U8–U12"),
("Spielformen", "Minitore-Spiel", "Viele kleine Tore", "20 Min", "U8–U12"),
("Spielformen", "Spiel ohne Dribbeln", "Passspiel forcieren", "25 Min", "U11–U14"),
("Spielformen", "Ein-Kontakt-Spiel", "Schnelles Spiel", "20 Min", "U13–U18"),
("Spielformen", "Überzahl-Spiel", "Klare Überzahl", "25 Min", "U13–U18"),
("Spielformen", "Regentage-Spiel", "Spielformen für die Halle", "20 Min", "U8–U12"),
("Spielformen", "Endzonen-Spiel", "Punkte in Zonen", "25 Min", "U13–U18"),
("Spielformen", "Turnier mit Aufgaben", "Aufgaben im Spiel", "25 Min", "U11–U14"),
("Spielformen", "Liga-Spieltag", "Mehrere Spiele", "30 Min", "U11–U18"),
("Spielformen", "Spiel mit Musik", "Spaß und Bewegung", "15 Min", "U8–U10"),
("Spielformen", "Königs-Team", "Sieger bleiben", "20 Min", "U8–U12"),
("Spielformen", "Doppel-Tor-Spiel", "Zwei Tore pro Team", "20 Min", "U11–U14"),
("Spielformen", "Spiel auf Zeit", "Kurze Wechsel", "20 Min", "U8–U12"),
("Spielformen", "Zahlen-Spiel", "Rufzahlen einbauen", "15 Min", "U8–U12"),
("Spielformen", "Saisonfinale-Turnier", "Abschlussturnier", "30 Min", "U8–U18"),
]